FROM node:lts-alpine AS build-front

RUN apk add --no-cache curl

WORKDIR /app

COPY ./client .

RUN npm ci \
    && npm run build

FROM node:lts-alpine

WORKDIR /app

RUN mkdir -p ./public

COPY --from=build-front /app/build/ ./public

COPY package*.json ./

RUN npm ci

COPY . .

CMD ["npm", "run", "skaffold"]
